apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gmtk2024
  name: gmtk2024
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gmtk2024
  template:
    metadata:
      labels:
        app: gmtk2024
      namespace: gmtk2024
      name: gmtk2024
    spec:
      containers:
        - name: gmtk2024
          image: ghcr.io/leemartin77/gmtk2024:ca7dcfb7561041c0b8dd84162b89b13abe5b86c7
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 80
